export const GET_DATA="GET_DATA"
export const SHOW_FILEDS_ERROR="SHOW_FIELDS_ERROR"
export const SUBMIT_USER_REGISTER_DATA="SUBMIT_USER_REGISTER_DATA"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"